name: CD Pipeline

on:
  workflow_dispatch:

jobs:
  deploying:
    runs-on: ubuntu-latest

    steps:
     

      - name: Checkout Code
        uses: actions/checkout@v3

     
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.S3_ID }}
          aws-secret-access-key: ${{ secrets.S3_KEY }}
          aws-region: ap-south-1  # Replace with your actual region
    
      - name: Upload to S3
        run: |
          aws s3 cp C:\Users\DELL\Devloper\React2\my-react-app s3://node--project/ --request-payer requester

