name: CD Pipeline

on:
  workflow_dispatch:

jobs:
  deploying:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v20.16.0

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Project
        run: |
          echo "Building the project..."
          npm install
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.S3_ID }}
          aws-secret-access-key: ${{ secrets.S3_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS S3
        run: |
          echo "Deploying to S3..."
          aws s3 sync ./build s3://Fiaz_Akhter --delete
