name: CD Pipeline

on:
  workflow_dispatch:

jobs:
  deploying:
    runs-on: ubuntu-latest

    steps:
     

      - name: Checkout Code
        uses: actions/checkout@v3

     
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.S3_ID }}
          aws-secret-access-key: ${{ secrets.S3_KEY }}
          aws-region: us-south-1  # Replace with your actual region

