name: Node.js CI

on:
  push:
    branches: ["local"]
  pull_request:
    branches: ["local"]
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [v20.16.0]   # Use the same version as setup-node below

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - run: sudo apt-get update
    - run: sudo apt-get install -y build-essential
    - run: npm install
    - run: npm run build   # Build command only, no need to start the app in CI
